name: Publish qilletni/tidal

on:
  workflow_dispatch: # For snapshot versions
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/qilletni/qilletni:snapshot

    steps:
      - uses: actions/checkout@v6

      - name: Clone Tidal SDK
        uses: actions/checkout@v6
        with:
          repository: Qilletni/tidal-sdk-android-standalone
          path: tidal-sdk-android-standalone

      # tidal-sdk-android-standalone uses Java 21 because of its kotlin dependency
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'

      # Qilletni packages use Java 22
      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v5

      - name: Build Tidal SDK
        working-directory: tidal-sdk-android-standalone
        run: |
          ./gradlew -x javadoc :common:publishToMavenLocal
          ./gradlew -x javadoc :tidalapi:publishToMavenLocal

      - name: Build Package
        run: qilletni build

      - name: QPM Publish
        run: qpm publish
        env:
          QPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: Qilletni/qilletni-package-docs
          event-type: update-docs
          client-payload: '{"package": "tidal"}'
